locale: "en-US"
title: "EphingAdmin"
title_separator: "-"
name: "Ryan Ephgrave"
description: "PowerShell tips and tricks"
#url:"https://ephingadmin.com"
gh_repo: "http://www.github.com/Ryan2065"

words_per_minute: 200


theme: jekyll-theme-slate