# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            EphingAdmin
tagline:          'A Jekyll theme'
description:      'Tips and Tricks for Windows Admins'
url:              https://ephingadmin.com
baseurl:          /

author:
  name:           'Ryan Ephgrave'
  url:            https://ephingadmin.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ryan2065
