# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            EphingAdmin
tagline:          'PowerShell tips and tricks'
description:      'Tips and Tricks for Windows Admins'
#url:              https://ephingadmin.com
url:              https://ryan2065.github.io/
baseurl:          /

author:
  name:           'Ryan Ephgrave'
  url:            https://ephingadmin.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Ryan2065/Ryan2065.github.io
